version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: arn:aws:ecs:ap-south-1:176275544602:task-definition/zust-login-td:2
        LoadBalancerInfo:
          ContainerName: zust-login-container
          ContainerPort: "9003"
        PlatformVersion: "LATEST"