version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:274201610284:task-definition/916568-pms-login-td:1"
        LoadBalancerInfo:
          ContainerName: "916568-pms-login-container"
          ContainerPort: "9003"
        PlatformVersion: "LATEST"