version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: $TD
        LoadBalancerInfo:
          ContainerName: $CONTAINER_NAME
          ContainerPort: "9003"
        PlatformVersion: "LATEST"